/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secundarias_gui;

/**
 *
 * @author Grupo 2
 */
public class Crear_Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Administrador
     */
    public Crear_Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JTextField();
        txt_compararContraseña = new javax.swing.JTextField();
        txt_nomUsuario = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        lb_cedula = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_apellido = new javax.swing.JLabel();
        lb_direccion = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        lb_nomUsuario = new javax.swing.JLabel();
        lb_contraseña = new javax.swing.JLabel();
        lb_compContraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_verificarContraseña = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cédula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 47, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Télefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 202, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 161, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Correo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 234, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Nombre de Usuario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 269, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Contraseña:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 307, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Repetir Contraseña:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 342, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("ADMINISTRADOR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 11, 125, -1));
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 44, 171, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 82, 171, -1));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 158, 171, -1));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 196, 171, -1));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 120, 171, -1));
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 304, 171, -1));
        getContentPane().add(txt_compararContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 336, 171, -1));
        getContentPane().add(txt_nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 266, 171, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 234, 171, -1));

        lb_cedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_cedula.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 44, -1, -1));

        lb_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_nombre.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 82, -1, -1));

        lb_apellido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_apellido.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 120, -1, -1));

        lb_direccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_direccion.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 158, -1, -1));

        lb_telefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_telefono.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 196, -1, -1));

        lb_correo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_correo.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 234, -1, -1));

        lb_nomUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_nomUsuario.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 266, -1, -1));

        lb_contraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_contraseña.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 304, -1, -1));

        lb_compContraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_compContraseña.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb_compContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 336, -1, -1));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 390, -1, -1));

        jButton2.setText("GUARDAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        lb_verificarContraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_verificarContraseña.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(lb_verificarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 336, -1, -1));

        jLabel11.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.pinimg.com/564x/84/92/7c/84927c8afc131a8de9b4a318ce95a2ed.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 560, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_cedula;
    private javax.swing.JLabel lb_compContraseña;
    private javax.swing.JLabel lb_contraseña;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_nomUsuario;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JLabel lb_verificarContraseña;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_compararContraseña;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nomUsuario;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
